# -*- coding: utf-8 -*-
"""Modelbuilding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwY7FlrTGTxcTQ4J3bvN-7rFR5qdq14l
"""

import pandas as pd

# Impute numerical columns with their mean
for col in ['Age', 'Years of Experience', 'Salary']:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mean())

# Impute categorical columns with their mode
for col in ['Gender', 'Education Level', 'Job Title']:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mode()[0])

print(f"Shape before dropping duplicates: {df.shape}")

df.drop_duplicates(inplace=True)

print(f"Shape after dropping duplicates: {df.shape}")

from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Apply Label Encoding to categorical columns
for col in ['Gender', 'Education Level', 'Job Title']:
    df[col] = le.fit_transform(df[col])

"""Now that label encoding has been applied, let's look at the first few rows of the DataFrame to see the changes."""

display(df.head())

df=pd.read_csv('/content/Salary_Data.csv')

df

df.info

df.info()

df.isnull().sum()

df.drop_duplicates()



# Separate features (X) and target (y)
X = df.drop('Salary', axis=1)
y = df['Salary']

print("Features (X) shape:", X.shape)
print("Target (y) shape:", y.shape)

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets (e.g., 80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

from sklearn.linear_model import LinearRegression

# Initialize the Linear Regression model
linear_model = LinearRegression()

# Train the model using the training data
linear_model.fit(X_train, y_train)

print("Linear Regression model trained successfully!")

"""## Train Decision Tree Regressor"""

from sklearn.tree import DecisionTreeRegressor

# Initialize the Decision Tree Regressor model
decision_tree_model = DecisionTreeRegressor(random_state=42)

# Train the model using the training data
decision_tree_model.fit(X_train, y_train)

print("Decision Tree Regressor model trained successfully!")

"""## Train Random Forest Regressor"""

from sklearn.ensemble import RandomForestRegressor

# Initialize the Random Forest Regressor model
random_forest_model = RandomForestRegressor(random_state=42)

# Train the model using the training data
random_forest_model.fit(X_train, y_train)

print("Random Forest Regressor model trained successfully!")

"""## Train K-Nearest Neighbors Regressor"""

from sklearn.neighbors import KNeighborsRegressor

# Initialize the K-Nearest Neighbors Regressor model
# You might need to tune the 'n_neighbors' parameter
knn_model = KNeighborsRegressor(n_neighbors=5)

# Train the model using the training data
knn_model.fit(X_train, y_train)

print("K-Nearest Neighbors Regressor model trained successfully!")

"""## Train Support Vector Machine (SVM) Regressor"""

from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# SVMs are sensitive to feature scaling, so we'll use a pipeline with StandardScaler
# Initialize the SVM Regressor model
svm_model = Pipeline([
    ('scaler', StandardScaler()),
    ('regressor', SVR(kernel='rbf')) # Radial Basis Function kernel is a common choice
])

# Train the model using the training data
svm_model.fit(X_train, y_train)

print("Support Vector Machine (SVM) Regressor model trained successfully!")

"""## Evaluate and Visualize Model Performance"""

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt
import seaborn as sns

# Make predictions on the test set for each model
y_pred_linear = linear_model.predict(X_test)
y_pred_decision_tree = decision_tree_model.predict(X_test)
y_pred_random_forest = random_forest_model.predict(X_test)
y_pred_knn = knn_model.predict(X_test)
y_pred_svm = svm_model.predict(X_test)

# Calculate R-squared for each model
r2_linear = r2_score(y_test, y_pred_linear)
r2_decision_tree = r2_score(y_test, y_pred_decision_tree)
r2_random_forest = r2_score(y_test, y_pred_random_forest)
r2_knn = r2_score(y_test, y_pred_knn)
r2_svm = r2_score(y_test, y_pred_svm)

# Store results in a dictionary for easy comparison
model_performance = {
    'Linear Regression': r2_linear,
    'Decision Tree': r2_decision_tree,
    'Random Forest': r2_random_forest,
    'K-Nearest Neighbors': r2_knn,
    'SVM': r2_svm
}

# Convert to DataFrame for plotting
performance_df = pd.DataFrame(list(model_performance.items()), columns=['Model', 'R2 Score'])

print("R-squared scores:")
print(performance_df)

# Visualize R-squared scores
plt.figure(figsize=(12, 7))
sns.barplot(x='R2 Score', y='Model', data=performance_df, palette='viridis')
plt.title('R-squared Score Comparison Across Models')
plt.xlabel('R-squared Score')
plt.ylabel('Model')
plt.xlim(0, 1) # R-squared typically ranges from 0 to 1 for good models
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""## Model Performance Comparison"""

# Display the performance DataFrame to compare R-squared scores
display(performance_df)

"""As you can see, the **Random Forest** model has the highest R-squared score, indicating it explains the most variance in the `Salary` target variable among the models tested. **K-Nearest Neighbors** also shows strong performance. The **SVM** model performed poorly, suggesting it might require more specific tuning or a different approach for this dataset. The bar chart above provides a visual representation of this comparison."""

import pickle

# Define the filename for the saved model
model_filename = 'random_forest_regressor_best_model.pkl'

# Save the best model (Random Forest Regressor) to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(random_forest_model, file)

print(f"Best model (Random Forest Regressor) saved to {model_filename}")